#!/bin/bash

# Check Convex Logs for Authentication Activity
# This script provides instructions for checking Convex logs

echo "🔍 Convex Authentication Logs Checker"
echo "======================================"
echo ""
echo "To check if authentication is working on the backend:"
echo ""
echo "1. Open Convex Dashboard:"
echo "   https://dashboard.convex.dev/"
echo ""
echo "2. Select your deployment:"
echo "   resolute-tern-881.convex.cloud"
echo ""
echo "3. Go to 'Logs' tab"
echo ""
echo "4. Look for these log entries:"
echo ""
echo "   ✅ SUCCESS LOGS:"
echo "   - 'createVerificationCodeImpl args' - Code generated"
echo "   - 'Generated token' - Authentication succeeded"
echo "   - 'refresh token' - Session created"
echo "   - 'defaultCreateOrUpdateUser args' - User created/updated"
echo "   - 'Calling custom afterUserCreatedOrUpdated callback' - Timestamps set"
echo ""
echo "   ❌ ERROR LOGS:"
echo "   - 'Could not verify code' - Invalid/expired/used code"
echo "   - 'Missing environment variable' - Configuration issue"
echo "   - 'Failed to send magic link' - Email sending failed"
echo ""
echo "5. Filter logs by function:"
echo "   - auth:signIn - Authentication attempts"
echo "   - auth:store - User creation/updates"
echo ""
echo "6. Check environment variables:"
echo "   npx convex env list"
echo ""
echo "Expected environment variables:"
echo "   - SITE_URL=http://localhost:8081/auth/callback"
echo "   - AUTH_RESEND_KEY=re_XA3kYNY8_DSdFGMmwdttWk7Pk8dftHHDn"
echo "   - AUTH_LOG_LEVEL=DEBUG"
echo "   - JWT_PRIVATE_KEY=[Set]"
echo ""
echo "======================================"
echo "💡 TIP: Keep the Convex dashboard open while testing"
echo "    to see real-time logs as you click the magic link!"
echo "======================================"
